apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
      <body>
        <h1>Welcome to Advanced Kubernetes!</h1>
        <p>This page is served from a ConfigMap.</p>
      </body>
    </html>